### ISSUE TITLE
Svalinn insert queue maxing out at 13k

### ISSUE THREAD

**Issue by kristinaspring** [Comcast/codex-svalinn#36]
This queue should be configurable, but when the value is set to 3000 in the configuration, it still goes up to 13,000.

**Comment by kcajmagic** [comment]
What appears to be happening is `maxParseWorkers` (set to 10,000) and `parseQueueSize` ( set to 3,000) are somehow being combined to give us our metric of a full queue of 13,000.

**Comment by kristinaspring** [comment]
The number was the sum of `maxParseWorkers` and `insertQueueSize`, because the parse workers added to the metric before inserting to the queue, so blocked when the queue was full.
